image:
  name: blueacornici/magento-services:v2-pipelines-7.4composer2
  username: $DOCKER_USER
  password: $DOCKER_PASS
definitions:
  caches:
    node: node_modules
    composer: .composer
  services:
    docker:
      memory: 4096
pipelines:
  custom:
    auto-db-snapshot:
      - step:
          name: Database Snapshot
          script: [ source init, snapshot ]
          services: [ docker ]
    auto-provision:
      - step:
          name: Provision in AWS
          script: [ source init, provision ]
          services: [ docker ]
  default:
      - step:
          name: Initialize Deployment
          deployment: auto
          trigger: automatic
          script: [ source init ]
      - parallel:
        - step:
            name: "2.4.0 Magento Open Source"
            size: 2x
            script: [
                export AUTO_IMAGE_TYPE=7.4c,
                export AUTO_USE_EXAMPLE=2.4.0-ce,
                export AUTO_TESTS_ALWAYS_PASS=true,

                source init, build, best-practices, deploy, mftf, conclude

            ]
            services: [ docker ] 
        - step:
            name: "Adobe Commerce 2.4.3"
            size: 2x
            script: [
                export AUTO_IMAGE_TYPE=7.4composer2,
                export AUTO_USE_EXAMPLE=2.4.3-ee,
                export AUTO_TESTS_ALWAYS_PASS=true,

                source init, build, best-practices, deploy, mftf, conclude

            ]
            services: [ docker ] 
      - step:
          name: Deployment Complete
          script: [ source init, complete ]
      - step:
          name: Destroy
          trigger: manual
          size: 2x
          script: [ source init, destroy ]
          services: [ docker ]


