<?php
/**
 * @author    Blue Acorn iCi <code@blueacornici.com>
 * @copyright 2021 Blue Acorn iCi. All Rights Reserved.
 */

use PayYourWay\Pyw\Block\Adminhtml\System\Config\ChangeClientId;

/**
 * @var ChangeClientId $block
 */
?>
<script>
    require([
        'jquery'
    ], function ($) {
        function changeClientIdButton() {
            $('#payment_us_payyourway_client_id_sb').prop("disabled", false);
        }

        $('#change_client_id').click(function () {
            changeClientIdButton();
        });

    });
</script>

<div id="messages-clientid-change">
    <div class="messages">
        <div class="message message-success success" style="display: none;">
            <div data-ui-id="messages-message-success">
                <span class="message-text"></span>
            </div>
        </div>
        <div class="message message-error error" style="display: none;">
            <div data-ui-id="messages-message-error">
                <span class="message-text"></span>
            </div>
        </div>
    </div>
</div>
<?php echo $block->getButtonHtml() ?>
