<?php
/**
 * @author    Blue Acorn iCi <code@blueacornici.com>
 * @copyright 2021 Blue Acorn iCi. All Rights Reserved.
 */

use PayYourWay\Pyw\Block\Adminhtml\System\Config\GenerateClientId;

/**
 * @var GenerateClientId $block
 */
?>
<script>
    require([
        'jquery',
        'mage/translate',
        'Magento_Ui/js/modal/alert',
        'domReady!'
    ], function ($,$t,malert) {
        function generateClientIdButton() {
            let clientIdSb = $('[data-ui-id="text-groups-payyourway-groups-settings-fields-client-id-sb-value"]');
            let clientIdPr = $('[data-ui-id="text-groups-payyourway-groups-settings-fields-client-id-pr-value"]');
            let merchantNameSb =
                $('[data-ui-id="text-groups-payyourway-groups-register-fields-merchant-name-sb-value"]');
            let merchantNamePr =
                $('[data-ui-id="text-groups-payyourway-groups-register-fields-merchant-name-pr-value"]');
            let environment = $('[data-ui-id="select-groups-payyourway-groups-settings-fields-environment-value"]');
            if (environment.val() === 'sandbox') {
                if (merchantNameSb.val() === '') {
                    malert({
                        title: $t('There is an error with your request'),
                        content:  $t('Please add a Sandbox Merchant Name')
                    });
                }
                let merchantName = merchantNameSb.val();
                let clientId = 'MG_'+merchantName.replace(/\s/g, '')+'_QA';
                clientIdSb.val(clientId);
            } else {
                if (merchantNamePr.val() === '') {
                    malert({
                        title: $t('There is an error with your request'),
                        content:  $t('Please add a Merchant Name')
                    });
                }
                let merchantName = merchantNamePr.val();
                let clientId = 'MG_'+merchantName.replace(/\s/g, '');
                clientIdPr.val(clientId);
            }

        }

        $('#generate_client_id').click(function () {
            generateClientIdButton();
        });
    });
</script>

<div id="messages-clientid-generate">
    <div class="messages">
        <div class="message message-success success" style="display: none;">
            <div data-ui-id="messages-message-success">
                <span class="message-text"></span>
            </div>
        </div>
        <div class="message message-error error" style="display: none;">
            <div data-ui-id="messages-message-error">
                <span class="message-text"></span>
            </div>
        </div>
    </div>
</div>
<?= /* @noEscape */ $block->getButtonHtml() ?>

