<?php
/**
 * @author    Blue Acorn iCi <code@blueacornici.com>
 * @copyright 2021 Blue Acorn iCi. All Rights Reserved.
 */

/**
 * @var PayYourWay\Pyw\Block\Adminhtml\System\Config\KeyGenerator $block
 */
?>
<script>
    require([
        'jquery'
    ], function ($) {
        function generateAccessToken() {
            $.ajax({
                type: 'POST',
                url: '<?=  /* @noEscape */ $block->getAccessTokenUrl() ?>',
                dataType: 'json',
                data: {form_key: '<?= /* @noEscape */ $block->getFormKey() ?>'},
                contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                showLoader:true,
                success: function() {
                    let messageSuccess = $('#messages .message-success');
                    $('#messages .message-success span.message-text').text('Access Token Saved Successfully');
                    messageSuccess.show();
                    messageSuccess.delay(8000).fadeOut();
                },
                onFailure: function() {
                    let messageError =  $('#messages .message-error');
                    $('#messages .message-error span.message-text').text('Failed');
                    messageError.show();
                    messageError.delay(8000).fadeOut();
                    return false;
                }
            })
        }
        $('#generate_access_token').click(function () {
            generateAccessToken();
        });
    });
</script>

<div id="messages" >
    <div class="messages">
        <div class="message message-success success" style="display: none;">
            <div data-ui-id="messages-message-success">
                <span class="message-text"></span>
            </div>
        </div>
        <div class="message message-error error" style="display: none;">
            <div data-ui-id="messages-message-error">
                <span class="message-text"></span>
            </div>
        </div>
    </div>
</div>
<?= /* @noEscape */ $block->getButtonHtml() ?>
